[package]
name = "p0f-parser"
version = "0.1.0"
authors = ["jgrmnprz <jgrmnprz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
nom = "^5"
chrono = "^0.4"
